--REQUEREMIENTO 1
SELECT C.SUCURSAL,SUM(D.TOTALPAGADO)AS TOTAL
FROM(
SELECT *
FROM(
SELECT *
FROM A_ESTANTE )A INNER JOIN A_PRODUCTOSUCURSAL B ON A.IDESTANTE=B.ESTANTE) C INNER JOIN A_COMPRA D 
ON c.IDPRODUCTOSUCURSAL = d.productosucursal
WHERE FECHA BETWEEN 0 AND 1 
GROUP BY C.SUCURSAL;

--requerimiento 3
SELECT SUM(B.VOLUMENEMPAQUE)/A.VOLUMEN AS INDICE_USO,A.IDBODEGA
FROM(
SELECT *
FROM A_BODEGA ) A INNER JOIN A_PRODUCTOSUCURSAL B ON A.IDBODEGA = B.BODEGA
GROUP BY A.VOLUMEN,A.IDBODEGA;

SELECT SUM(B.VOLUMENEMPAQUE)/A.VOLUMEN AS INDICE_USO,A.IDESTANTE
FROM(
SELECT *
FROM A_ESTANTE ) A INNER JOIN A_PRODUCTOSUCURSAL B ON A.IDESTANTE = B.ESTANTE
GROUP BY A.VOLUMEN,A.IDESTANTE;
--REQUEREMIENTO 4
--PRODUTO POR PESO
SELECT*
FROM A_PRODUCTOSUCURSAL
WHERE PESOEMPAQUE BETWEEN 1 AND 2;

--PRODUCTO POR VOLUMEN
SELECT*
FROM A_PRODUCTOSUCURSAL
WHERE VOLUMENEMPAQUE BETWEEN 1 AND 2;

--PRODUCTO POR CATEGORIA
SELECT *
FROM A_PRODUCTOSUCURSAL 
WHERE CATEGORIA =;

--PRODUCTO POR TIPO
SELECT *
FROM A_PRODUCTOSUCURSAL 
WHERE TIPO =;

--PRODUCTO POR CIUDAD
SELECT B.*
FROM(
SELECT *
FROM(
SELECT *
FROM A_SUCURSAL) D INNER JOIN A_ESTANTE F ON D.IDSUCURSAL = F.SUCURSAL) A INNER JOIN A_PRODUCTOSUCURSAL B ON A.IDESTANTE = B.ESTANTE 
WHERE A.CIUDAD = ;

--PRODUCTO POR SUCURSAL
SELECT B.*
FROM(
SELECT *
FROM(
SELECT *
FROM A_SUCURSAL) D INNER JOIN A_ESTANTE F ON D.IDSUCURSAL = F.SUCURSAL) A INNER JOIN A_PRODUCTOSUCURSAL B ON A.IDESTANTE = B.ESTANTE 
WHERE A.SUCURSAL = ;

